export const FETCH_BLOG_POSTS_REQUEST = "FETCH_BLOG_POSTS_REQUEST";
export const FETCH_BLOG_POSTS_SUCCESS = "FETCH_BLOG_POSTS_SUCCESS";
export const FETCH_BLOG_POSTS_FAILURE = "FETCH_BLOG_POSTS_FAILURE";

// this is asynchrounous call

export const FETCH_SINGLE_BLOG_REQUEST = "FETCH_SINGLE_BLOG_REQUEST";
export const FETCH_SINGLE_BLOG_SUCCESS = "FETCH_SINGLE_BLOG_SUCCESS";
export const FETCH_SINGLE_BLOG_FAILURE = "FETCH_SINGLE_BLOG_FAILURE";

// for create application / blog

export const CREATE_BLOG_POST_REQUEST = "CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_SUCCESS = "CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAILURE = "CREATE_BLOG_POST_FAILURE";

export const UPDATE_BLOG_POST_REQUEST = "UPDATE_BLOG_POST_REQUEST";
export const UPDATE_BLOG_POST_SUCCESS = "UPDATE_BLOG_POST_SUCCESS";
export const UPDATE_BLOG_POST_FAILURE = "UPDATE_BLOG_POST_FAILURE";
