
export const COUNTRYLOAD = "COUNTRYLOAD";
export const COUNTRYFETCH = "COUNTRYFETCH";
export const COUNTRYFAIL = "COUNTRYFAIL";

export const LIGHTTHEME = "LIGHTTHEME";
export const DARKTHEME = 'DARKTHEME';